### ISSUE TITLE
[BUG]: Every morning immediately when I start octoprint & printer, I get my 60sec Abort Power Off Timeout on Idle even though the 30min idle did not happen

### ISSUE THREAD

**Issue by LarryVand** [jneilliii/OctoPrint-TPLinkSmartplug#202] opened 2020-08-11 12:46 UTC
**Describe the bug**
I have my 3D printer (Artillery X1) and Octoprint plugged in on the same TP-Link HS-100 power plug. Every morning I turn the plug ON by either manually hitting the ON button on the plug or the ON button on the Kasa app. And immediately when Octoprint is up on my screen, I have the 60 Sec Abort Power Off Timeout on Idle (Idle Timeout is set to 30min). If I let the 60sec timeout finish, Octoprint shutsdown and the TP-Link plug turns off powering off the printer and Octoprint (normal behavior as expected). Restarting again by turning on the Plug (manually or via the Kasa app)  does NOT give me the 60 Sec Abort Power Off Timeout on Idle. **In other words, the bug only happens on the first start.**

**Expected behavior**
On the first start, the 60 Sec Abort Power Off Timeout on Idle should not appear till after the 30min idle time had passed.

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome
 - OctoPrint 1.4.2 Python 2.7.16 OctoPi 0.17.0
 - TP-Link Smartplug (0.9.24)

**Screenshots**
![tp1](https://user-images.githubusercontent.com/69426512/89898374-73585400-db95-11ea-820e-8304b2741d03.JPG)
![tp2](https://user-images.githubusercontent.com/69426512/89898393-7f441600-db95-11ea-8532-605dd1f82f17.JPG)

**Comment by jneilliii** [comment] 2020-08-11 13:17
Duplicate of #171

**Closed by jneilliii** 2020-08-11 13:17 UTC
