### ISSUE TITLE
Disappearing sidebar?

### ISSUE THREAD

**Issue by Jozer99** [jneilliii/OctoPrint-TPLinkSmartplug#83] opened 2019-01-14 02:05 UTC
Firstly, thank you for the plugin, I love having the TP-Link control functionality in Octoprint.  

I notice that when I load the octoprint webpage in my browser, a side panel box with the current power consumption of the TP link plug is displayed.  This sidebar disappears when the page fully loads.  How do I get this sidebar box to stay around? I think having the power consumption of the printer displayed would be interesting.  Looking at the page source, the div "sidebar_plugin_tplinksmartplug_wrapper" is set to "display: none".

**Comment by Jozer99** [comment] 2019-01-15 00:40
My smartplug is an HS-110, and the TP-Link app provides information on power usage.  The sidebar panel still disappears.

**Comment by jneilliii** [comment] 2019-01-15 02:05
Can you enable debug logging in settings, restart octoprint, force a refresh of the browser (ctrl + F5) and then report back here with your plugin_tplinksmartplug_debug.log file please?

**Comment by Dalewn** [comment] 2019-01-19 20:16
Just saw the same behaviour. I only own a HS100, so sadly it is intended behaviour.

One a sidenote: Maybe add a note to your description as it is not clear that the HS110's power usage actually is supported.

**Comment by jneilliii** [comment] 2019-01-19 20:41
Good point @Dalewn, I haven't updated the readme with screenshots or details about that.  I'll add that to my todo list for the next update.

**Comment by kalle-1989** [comment] 2019-01-19 23:16
I have an HS110 and also the same issue with the disappearing sidebar panel for power consumption. I attache my log with removed IP und 
[plugin_tplinksmartplug_debug.log](https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/files/2776085/plugin_tplinksmartplug_debug.log)
Ids.

**Comment by jneilliii** [comment] 2019-01-20 01:36
That's weird, I'll have to go back and review the code, but it should be working because it's returning the information for the plug for sure.  The last line toward the very end is the energy data.

```
"emeter":{"get_realtime":{"voltage_mv":233653,"current_ma":19,"power_mw":0,"total_wh":85,"err_code":0}}
```

Have you by chance tried restarting octoprint since setting up the plug?

**Comment by Jozer99** [comment] 2019-01-20 03:39
I enabled debugging.  How do I find the debug log file and get it off the pi?

**Comment by Jozer99** [comment] 2019-01-20 03:45
Here is my log, as requested.  
[plugin_tplinksmartplug_debug.log](https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/files/2776238/plugin_tplinksmartplug_debug.log)

**Comment by jneilliii** [comment] 2019-01-20 03:47
@Jozer99 that looks like an exact copy of @kalle-1989 log file. The timestamps are even exactly the same.

**Comment by Jozer99** [comment] 2019-01-20 03:55
Opps, uploaded the wrong log file.  Here is the real one, I hope.  
[plugin_tplinksmartplug_debug.anon.log](https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/files/2776260/plugin_tplinksmartplug_debug.anon.log)

**Comment by jneilliii** [comment] 2019-01-20 04:01
yep, I see it returning the correct data back.  Have you tried restarting octoprint since adding the plug in settings?

**Comment by Jozer99** [comment] 2019-01-20 04:10
I've had the plugin with these settings for months.  I have restarted it several times today.  The energy monitor sidebar panel disapears during page load still.

**Comment by jneilliii** [comment] 2019-01-20 04:19
Thanks.  If you ssh to your pi and open `~/.octoprint/config.yaml` does the plugin settings show the emeter data saved with the plug?

**Comment by jneilliii** [comment] 2019-01-20 05:45
Thanks.  For some reason the emeter section isn't updating from what's returned by the plug when the plugin checks the status. Were you using a version prior to 0.9.8? I'd like trying deleting the entire tplinksmartplug section from config.yaml and then restart octoprint and reconfigure the plug in settings.

**Comment by jneilliii** [comment] 2019-01-20 06:04
I think I see the issue now.  It's definitely related to code issues on the plugin side.  I'm looking into possible fixes now.

**Comment by jneilliii** [comment] 2019-01-27 08:11
Could you guys test a potential fix for this issue by installing an updated version using the url below in plugin manager?  So far my testing has proven positive, would love to get some additional feedback prior to officially releasing it.

https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/archive/0.9.11.zip

**Comment by alexisju** [comment] 2019-02-03 10:36
Worked for me with the 0.9.11 (didnt worked previously with my HS110(FR))

sysinfo":{"err_code":0,"sw_ver":"1.2.5 Build 180410 Rel.182657","hw_ver":"1.0","type":"IOT.SMARTPLUGSWITCH","model":"HS110(FR)

**Comment by jneilliii** [comment] 2019-02-09 17:33
Version 0.9.11 officially released.  Thanks @alexisju for confirmation. I still want to split out the energy monitoring request to display accurately, to fix the issue where the sidebar data displays the plug as still drawing power when it's off and should show 0.

**Closed** 2019-02-09 17:33 UTC

**Comment by Jozer99** [comment] 2019-02-10 02:53
I can verify that it is now working correctly.  Thank you jneilliii for your plugin, and your excellent assistance with this issue.
